### ISSUE TITLE
Can't git pull the repo

### ISSUE THREAD

**Issue by swissman777** [JetsGame/GroomRL#10]
As the title says. I followed the instructions and did "git clone https://github.com/JetGames/groomrl.git" and after I signed in, it gave this error "remote: Repository not found."

I also tried to directly copy the https link on the github page, which is apparently different ("https://github.com/JetsGame/GroomRL.git") because that just flat out just gave fatal, not a git repository error. 

Fortunately, I am able to download the zip file. However, it would be really great if this problem could be solved.

**Comment by fdreyer** [comment]
Hello,

There was a small typo in the readme. The proper command is:
git clone https://github.com/JetsGame/GroomRL.git

Thanks for pointing this out.

Best,
Frédéric


Le mer. 27 mars 2019 à 22:35, swissman777 <notifications@github.com> a
écrit :
