### ISSUE TITLE
Obtaining Training Data

### ISSUE THREAD

**Issue by swissman777** [JetsGame/GroomRL#11]
Hello, I was trying to train the model from scratch and realized that there was no training data in this repo. I realize that the data was simulated through Pythia, but I have never used the software so I don't know how to use it to obtain the training data. This may be a reach, but would it be possible to obtain one of the already-made training data? (files like WW_500GeV.json.gz for example)

Thank you in advance

**Comment by fdreyer** [comment]
Hi swissman777,

Actually, all the data is already available :) it is in a separate git-lfs repo due to the large size and number of files: https://github.com/JetsGame/data

Cheers,
Frédéric
