### ISSUE TITLE
Having issue installing and importing fastjet in python 3

### ISSUE THREAD

**Issue by swissman777** [JetsGame/GroomRL#12]
Really sorry to bother you again, but I am having trouble trying to import fastjet.
I have followed the official fastjet installation guide and basically typed this:
./configure --prefix=‘pwd‘/../fastjet-install
make
sudo make install
Then I received a folder called fastjet-install. There, I found "site-packages" folder in the fastjet-install/lib/python2.7 folder. Since I am using Anaconda3, I basically copy pasted the site-packages folder to Anaconda's own site-packages folder (basically adding fastjet to path). 

The problem is that when I try to import all from fastjet.py file, python give this error:  "No module named '_fastjet'" 
I played around with different ways to play around with the pathing, but with no avail. How did you import fastjet, for python3 at that (bc officially python 2.7 is the supported version)?

Thanks in advance

**Comment by scarrazza** [comment]
You should run `configure` with the extra `--enable-pyext` flag.

**Comment by swissman777** [comment]
> 
> 
> You should run `configure` with the extra `--enable-pyext` flag.

Whoops, I forgot to tell you that I did that too. So the actual line was ./configure --prefix=‘pwd‘/../fastjet-install --enable-pyext

**Comment by scarrazza** [comment]
Instead of copy/paste, make sure the environment variables `PYTHONPATH` and `LD_LIBRARY_PATH` are set properly.

**Comment by swissman777** [comment]
So I should set both pythonpath and le_library_path to the fastjet-install folder?

**Comment by scarrazza** [comment]
LD_LIBRARY_PATH should point to your fastjet-install/lib folder
PYTHONPATH to fastjet-install/lib/python3.x/site-packages

However, I suggest to install fastjet directly in your anaconda prefix, i.e. `./configure --prefix=$CONDA_PREFIX --enable-pyext`, so everything should work automatically.

**Comment by scarrazza** [comment]
More explicitly:
```bash
export LD_LIBRARY_PATH=<path to your install>/lib:$LD_LIBRARY_PATH
export PYTHONPATH=<path to your install>/lib/python3.x/site-packages:$PYTHONPATH
```
Make sure the python3.<some number> exists, otherwise this means that you have not compiled with a python3 interpreter.
